# Site settings
title: Yuchen "Reese" Sun
description: 'KINS 341 Final Project: History of Basketball'
url: 'http://wodeni.github.io/reese-site'
baseurl: '/reese-site/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Reese Yuchen Sun'
  email: yxs246@psu.edu
  # twitter_username: joshgerdes
  # facebook_username: joshgerdes
  # github_username:  wodeni
  # linkedin_username:  wode-ni

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
